server.port=8086

# Salida del Excel
balances-afp-patrimonios.salidas-dir=./salidas
balances-afp-patrimonios.guardar-copia-local=true
balances-afp-patrimonios.max-poi-file-mb=80

# Reglas generales
balances-afp-patrimonios.tipo-entidad=23
balances-afp-patrimonios.estado-entidad-vigente=1
balances-afp-patrimonios.tipo-patrimonio=6
balances-afp-patrimonios.tipo-informe=17

#Corto Plazo
balances-afp-patrimonios.tipo-patrimonio-cesantias-corto-plazo=5
balances-afp-patrimonios.codigo-patrimonio-cesantias-corto-plazo=2

#Laargo Plazo
balances-afp-patrimonios.tipo-patrimonio-cesantias-largo-plazo=5
balances-afp-patrimonios.codigo-patrimonio-cesantias-largo-plazo=1

# Total Cesantias (corto + largo plazo)
balances-afp-patrimonios.codigos-patrimonio-cesantias-total=1,2

# Conservador
balances-afp-patrimonios.tipo-patrimonio-conservador=6
balances-afp-patrimonios.codigo-patrimonio-conservador=5000

# Mayor Riesgo
balances-afp-patrimonios.tipo-patrimonio-mayor-riesgo=6
balances-afp-patrimonios.codigo-patrimonio-mayor-riesgo=6000

# Skandia
balances-afp-patrimonios.codigo-entidad-skandia=9

# Cuentas PUC
balances-afp-patrimonios.codigos-puc=100000,110000,110500,110505,110510,110515,110520

# Patrimonios comunes para cualquier entidad
balances-afp-patrimonios.codigos-patrimonio-obligatorio=1000,5000,6000,7000,8000

# Patrimonios adicionales permitidos únicamente para Skandia
balances-afp-patrimonios.codigos-patrimonio-adicional-skandia=4

# Patrimonios de Skandia que se presentan en SKANDIA_ALT
balances-afp-patrimonios.codigos-patrimonio-skandia-alternativo=4,8000

# Conexión exclusiva de BalancesAFPPatrimonios
balances-afp-patrimonios.datasource.url=jdbc:teradata://10.40.176.8/DATABASE=prod_dwh_consulta,LOGMECH=LDAP
balances-afp-patrimonios.datasource.driver-class-name=com.teradata.jdbc.TeraDriver
balances-afp-patrimonios.datasource.username=${BALANCES_AFP_PATRIMONIOS_DB_USER:}
balances-afp-patrimonios.datasource.password=${BALANCES_AFP_PATRIMONIOS_DB_PASSWORD:}

balances-afp-patrimonios.datasource.maximum-pool-size=4
balances-afp-patrimonios.datasource.minimum-idle=1
balances-afp-patrimonios.datasource.connection-timeout=30000
balances-afp-patrimonios.datasource.validation-timeout=5000
balances-afp-patrimonios.datasource.initialization-fail-timeout=1

#Tiempo de respuesta del query
balances-afp-patrimonios.datasource.query-timeout-seconds=900

# Dos intentos totales: ejecución inicial y un reintento
balances-afp-patrimonios.datasource.max-query-attempts=2

# Espera de 3 segundos antes del reintento
balances-afp-patrimonios.datasource.retry-delay-ms=3000



logging.level.root=INFO
logging.level.co.gov.sfc.balancesafppatrimonios=INFO

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
spring.thymeleaf.cache=false

# Moderado
balances-afp-patrimonios.tipo-patrimonio-moderado=6
balances-afp-patrimonios.codigo-patrimonio-moderado=1000
